import Navbar from "@/components/navbar";
import "./globals.css";
import Footer from "@/components/footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body  className="container m-auto">
        <Navbar />
        {children}
        <Footer />
        </body>
    </html>
  );
}
